version: '3.8'

services:
  dev:
    container_name: javelin_broker_dev_container
    image: ydfd/javelin-broker-dev-image:1.0.0
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    command: yarn start:dev
    env_file: .env.development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
  prod:
    container_name: javelin_broker_prod_container
    image: ydfd/javelin-broker-prod-image:1.0.0
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    command: yarn start:prod
    env_file:
      - .env.production
    ports:
      - 3003:3000
    volumes:
      - .:/app
      - /app/node_modules